import typing as t

from .calculated_value import CalculatedValue

class InterpolationField[T = t.Any]:
    def __init__(
        self,
        interpolation_func: t.Callable[[T, T, float], T],
        delay: CalculatedValue[float] | float,
        default: T = None,
        flash: bool = False,
    ) -> None: ...
    def get_value(self) -> T: ...
    @t.overload
    def set_value(self, value: T, /) -> t.Self: ...
    @t.overload
    def set_value(self, value: T, /, *, flash: bool) -> t.Self: ...
    @property
    def progress(self) -> float: ...
    @property
    def delay(self) -> float: ...
    @property
    def is_interpolated(self) -> bool: ...
    @property
    def next_value(self) -> T: ...
    @property
    def is_flash(self) -> bool: ...
    @is_flash.setter
    def is_flash(self, value: bool) -> None: ...

__all__ = ['InterpolationField']
